#!/usr/bin/env python3
"""Generate the compact Kulla--Conty GGX directional-albedo tables.

The table integrates the unit-Fresnel, height-correlated Smith GGX BRDF by
sampling the visible-normal distribution.  The generated values are consumed
by both the C++ and CUDA implementations; OpenGL uploads the same table in the
blue/alpha channels of its split-sum BRDF texture.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path


def radical_inverse(bits: int) -> float:
    bits = ((bits << 16) | (bits >> 16)) & 0xFFFFFFFF
    bits = (((bits & 0x55555555) << 1) | ((bits & 0xAAAAAAAA) >> 1)) & 0xFFFFFFFF
    bits = (((bits & 0x33333333) << 2) | ((bits & 0xCCCCCCCC) >> 2)) & 0xFFFFFFFF
    bits = (((bits & 0x0F0F0F0F) << 4) | ((bits & 0xF0F0F0F0) >> 4)) & 0xFFFFFFFF
    bits = (((bits & 0x00FF00FF) << 8) | ((bits & 0xFF00FF00) >> 8)) & 0xFFFFFFFF
    return bits * 2.3283064365386963e-10


def normalize(vector: tuple[float, float, float]) -> tuple[float, float, float]:
    length = math.sqrt(sum(component * component for component in vector))
    return tuple(component / length for component in vector)


def dot(first: tuple[float, float, float], second: tuple[float, float, float]) -> float:
    return sum(a * b for a, b in zip(first, second))


def cross(first: tuple[float, float, float], second: tuple[float, float, float]) -> tuple[float, float, float]:
    return (
        first[1] * second[2] - first[2] * second[1],
        first[2] * second[0] - first[0] * second[2],
        first[0] * second[1] - first[1] * second[0],
    )


def sample_visible_ggx(
    view: tuple[float, float, float], alpha: float, u1: float, u2: float
) -> tuple[float, float, float]:
    stretched = normalize((alpha * view[0], alpha * view[1], view[2]))
    length_squared = stretched[0] * stretched[0] + stretched[1] * stretched[1]
    tangent1 = (
        (-stretched[1] / math.sqrt(length_squared), stretched[0] / math.sqrt(length_squared), 0.0)
        if length_squared > 1.0e-20
        else (1.0, 0.0, 0.0)
    )
    tangent2 = cross(stretched, tangent1)
    radius = math.sqrt(u1)
    phi = 2.0 * math.pi * u2
    t1 = radius * math.cos(phi)
    t2 = radius * math.sin(phi)
    blend = 0.5 * (1.0 + stretched[2])
    t2 = (1.0 - blend) * math.sqrt(max(0.0, 1.0 - t1 * t1)) + blend * t2
    t3 = math.sqrt(max(0.0, 1.0 - t1 * t1 - t2 * t2))
    visible_normal = (
        tangent1[0] * t1 + tangent2[0] * t2 + stretched[0] * t3,
        tangent1[1] * t1 + tangent2[1] * t2 + stretched[1] * t3,
        tangent1[2] * t1 + tangent2[2] * t2 + stretched[2] * t3,
    )
    return normalize(
        (
            alpha * visible_normal[0],
            alpha * visible_normal[1],
            max(0.0, visible_normal[2]),
        )
    )


def smith_lambda(cosine: float, alpha: float) -> float:
    cosine_squared = max(cosine * cosine, 1.0e-20)
    tangent_squared = max(0.0, (1.0 - cosine_squared) / cosine_squared)
    return 0.5 * (math.sqrt(1.0 + alpha * alpha * tangent_squared) - 1.0)


def directional_albedo(cosine: float, roughness: float, sample_count: int) -> float:
    if roughness <= 0.0:
        return 1.0
    cosine = max(cosine, 1.0e-4)
    alpha = roughness * roughness
    view = (math.sqrt(max(0.0, 1.0 - cosine * cosine)), 0.0, cosine)
    lambda_view = smith_lambda(cosine, alpha)
    g1_view = 1.0 / (1.0 + lambda_view)
    accumulated = 0.0
    for sample_index in range(sample_count):
        half_vector = sample_visible_ggx(
            view,
            alpha,
            (sample_index + 0.5) / sample_count,
            radical_inverse(sample_index),
        )
        view_dot_half = dot(view, half_vector)
        incoming = tuple(2.0 * view_dot_half * component - view[index] for index, component in enumerate(half_vector))
        if incoming[2] <= 0.0:
            continue
        g2 = 1.0 / (1.0 + lambda_view + smith_lambda(incoming[2], alpha))
        accumulated += g2 / g1_view
    return min(max(accumulated / sample_count, 0.0), 1.0)


def average_albedo(row: list[float]) -> float:
    # Integrate the same piecewise-linear function used by the runtime lookup.
    segment_width = 1.0 / (len(row) - 1)
    integral = 0.0
    for index in range(len(row) - 1):
        lower = index * segment_width
        upper = (index + 1) * segment_width
        slope = (row[index + 1] - row[index]) / segment_width
        intercept = row[index] - slope * lower
        integral += (
            0.5 * intercept * (upper * upper - lower * lower)
            + slope * (upper * upper * upper - lower * lower * lower) / 3.0
        )
    return min(max(2.0 * integral, 0.0), 1.0)


def format_values(values: list[float], columns: int = 8) -> str:
    lines = [
        "// Generated by tools/generate_ggx_energy_lut.py; do not edit by hand."
    ]
    for offset in range(0, len(values), columns):
        lines.append(
            "    " + ", ".join(f"{value:.9f}f" for value in values[offset : offset + columns]) + ","
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--size", type=int, default=32)
    parser.add_argument("--samples", type=int, default=32768)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    if args.size < 2 or args.samples < 1:
        raise SystemExit("size must be at least 2 and samples must be positive")

    table: list[list[float]] = []
    for roughness_index in range(args.size):
        roughness = roughness_index / (args.size - 1)
        table.append(
            [
                directional_albedo(cosine_index / (args.size - 1), roughness, args.samples)
                for cosine_index in range(args.size)
            ]
        )
    averages = [average_albedo(row) for row in table]
    output_directory = args.root / "src" / "render" / "generated"
    output_directory.mkdir(parents=True, exist_ok=True)
    (output_directory / "ggx_directional_albedo_lut.inc").write_text(
        format_values([value for row in table for value in row]), encoding="utf-8"
    )
    (output_directory / "ggx_average_albedo_lut.inc").write_text(
        format_values(averages), encoding="utf-8"
    )


if __name__ == "__main__":
    main()
